version: '2.2'
services:
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  geckodriver:
      image: blueimp/geckodriver
      environment:
        - VNC_ENABLED=true
        - EXPOSE_X11=true
      ports:
        - 5900:5900
  hub:
      image: selenium/hub:3.0.1
      environment:
        GRID_BROWSER_TIMEOUT: 120000
        GRID_TIMEOUT: 120000
        VIRTUAL_HOST: selenium.hub.docker
      ports:
        - "4444:4444"
  firefox:
    image: selenium/node-firefox:3.0.1
    environment: &SELENIUM_NODE_ENV
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    depends_on:
      - hub
  chrome:
    image: selenium/node-chrome:3.0.1
    environment:
      <<: *SELENIUM_NODE_ENV
    depends_on:
      - hub
  chrome-debug:
      image: selenium/node-chrome-debug:3.0.1
      environment:
        <<: *SELENIUM_NODE_ENV
      ports:
        - "5900:5900"
      depends_on:
        - hub
  firefox-debug:
    image: selenium/node-firefox-debug:3.0.1
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5901:5900"
    depends_on:
      - hub
  nightwatch:
    build: .
    environment:
      - SELENIUM_HOST=hub
      - NODE_ENV=test
      - FIREFOX=${FIREFOX}
    volumes:
      - ./test:/home/node
      - ./entrypoint.sh:/usr/local/bin/entrypoint
      - ./videos:/home/node/videos
      - ./screenshots:/home/node/screenshots
      - ./reports:/home/node/reports
